pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    git clone https://github.com/imamit17/Terraform.git
  displayName: 'Run a multi-line script'
