
name: Inactive Users

on:
  workflow_dispatch

jobs:
  stale_branches:
    runs-on: ubuntu-latest
    steps:
    - name: Analyze User Activity
      id: analyze_user_activity
      uses: peter-murray/inactive-users-action@v1
      with:
        token: ${{ secrets.TOKEN }}
        organization: imamit17
        activity_days: 90
    - name: Save User Activity Report
      uses: actions/upload-artifact@v2
      with:
        name: reports
        path: |
          ${{ steps.analyze_user_activity.outputs.report_csv }}
          
    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.21.0
      with:
        channel-id: 'CHANNEL_ID'
        slack-message: "Inactive User List: ${{ steps.analyze_user_activity.outputs.report_csv }}"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
       

         
      


