name: inactive users

on:
  workflow_dispatch
  
jobs:

  audit_log:
    runs-on: ubuntu-latest
    name: Membership Audit Log

    - name: Membership Audit Log Action
      uses: svanboxel/org-audit-action@v1
      with:
        organization: 'octodemov2'
        token: '${{ secrets.TOKEN }}'
        samlIdentities: true
