# .github/workflows/stale-branches.yml

name: Stale Branches

on:
  schedule:
    - cron: '2 * * * *'
    
permissions:
  issues: write
  contents: write

jobs:
  stale_branches:
    runs-on: ubuntu-latest
    steps:
    - name: Stale Branches
      uses: crs-k/stale-branches@v2.0.1
      with:
        repo-token: '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'
        days-before-stale: 120
        days-before-delete: 180
        comment-updates: false
        max-issues: 20
        tag-committer: false
        stale-branch-label: 'stale branch 🗑️'
        compare-branches: 'info'
